# Nome da nossa automação
name: Build webOS App

# Gatilho: Quando o robô deve trabalhar?
# Ele vai rodar toda vez que você enviar ("push") uma alteração para o seu ramo "main".
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permite que você inicie manualmente também

# Tarefas: O que o robô deve fazer?
jobs:
  build:
    # O tipo de computador que o robô vai usar (um Linux Ubuntu novinho)
    runs-on: ubuntu-latest

    # A sequência de passos que o robô vai executar
    steps:
      # Passo 1: Baixar seu código para dentro do computador do robô
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Instalar o Node.js e o npm, que são necessários
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Uma versão estável do Node.js

      # Passo 3: Instalar as ferramentas da LG (o ares-cli)
      - name: Install webOS CLI
        run: sudo npm install -g @webos-tools/cli

      # Passo 4: O GRANDE FINAL - Empacotar o aplicativo
      - name: Package the application
        run: ares-package .

      # Passo 5: Fazer o upload do resultado (.ipk) para que você possa baixar
      - name: Upload IPK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: duckflix-app-ipk # O nome do arquivo que você verá para baixar
          path: com.duckflix.app_1.0.0_all.ipk # O nome exato do arquivo gerado
